-- Create payment_logs table for monitoring payment events
-- This table provides visibility into payment processing issues and debugging

CREATE TABLE IF NOT EXISTS payment_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL,
  order_number TEXT,
  event_type TEXT NOT NULL CHECK (event_type IN ('status_check', 'status_update', 'error', 'webhook_received', 'webhook_verified', 'webhook_processed', 'invoice_created', 'invoice_paid', 'invoice_expired', 'product_delivered')),
  old_status TEXT,
  new_status TEXT,
  provider_status TEXT,
  error_message TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_payment_logs_order_id ON payment_logs(order_id);
CREATE INDEX IF NOT EXISTS idx_payment_logs_event_type ON payment_logs(event_type);
CREATE INDEX IF NOT EXISTS idx_payment_logs_created_at ON payment_logs(created_at DESC);

-- Create index for filtering by time range
CREATE INDEX IF NOT EXISTS idx_payment_logs_created_at_event_type ON payment_logs(created_at DESC, event_type);

-- Add RLS policies (adjust based on your security requirements)
ALTER TABLE payment_logs ENABLE ROW LEVEL SECURITY;

-- Allow service role to insert logs
CREATE POLICY "Service role can insert payment logs"
  ON payment_logs
  FOR INSERT
  TO service_role
  WITH CHECK (true);

-- Allow service role to read all logs
CREATE POLICY "Service role can read payment logs"
  ON payment_logs
  FOR SELECT
  TO service_role
  USING (true);

-- Optionally allow authenticated users to read their own order logs
CREATE POLICY "Users can read their own payment logs"
  ON payment_logs
  FOR SELECT
  TO authenticated
  USING (
    order_id IN (
      SELECT id FROM orders WHERE profile_id = auth.uid()
    )
  );

-- Create a view for recent errors
CREATE OR REPLACE VIEW recent_payment_errors AS
SELECT
  order_id,
  order_number,
  event_type,
  error_message,
  metadata,
  created_at
FROM payment_logs
WHERE event_type = 'error'
ORDER BY created_at DESC
LIMIT 100;

-- Create a view for payment status changes
CREATE OR REPLACE VIEW payment_status_changes AS
SELECT
  order_id,
  order_number,
  old_status,
  new_status,
  provider_status,
  created_at
FROM payment_logs
WHERE event_type = 'status_update'
ORDER BY created_at DESC
LIMIT 100;
