-- Flexible seller-defined product specifications.
-- File metadata such as name, size, version, and upload date remains sourced
-- from product_files and is intentionally not duplicated here.

BEGIN;

CREATE TABLE public.product_specs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  product_id bigint NOT NULL,
  spec_name text NOT NULL,
  spec_value text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT product_specs_pkey PRIMARY KEY (id),
  CONSTRAINT product_specs_product_id_fkey
    FOREIGN KEY (product_id)
    REFERENCES public.products(id)
    ON DELETE CASCADE,
  CONSTRAINT product_specs_name_check CHECK (
    char_length(btrim(spec_name)) BETWEEN 1 AND 80
  ),
  CONSTRAINT product_specs_value_check CHECK (
    char_length(btrim(spec_value)) BETWEEN 1 AND 500
  ),
  CONSTRAINT product_specs_sort_order_check CHECK (
    sort_order BETWEEN 0 AND 9999
  )
);

CREATE INDEX product_specs_product_sort_idx
  ON public.product_specs (product_id, sort_order, id);

ALTER TABLE public.product_specs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read published product specifications"
  ON public.product_specs
  FOR SELECT
  TO public
  USING (
    EXISTS (
      SELECT 1
      FROM public.products
      WHERE products.id = product_specs.product_id
        AND products.status = 'published'
    )
  );

CREATE POLICY "Sellers can view own product specifications"
  ON public.product_specs
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.products
      JOIN public.sellers ON sellers.id = products.seller_id
      WHERE products.id = product_specs.product_id
        AND sellers.profile_id = auth.uid()
    )
  );

CREATE POLICY "Approved sellers can create own product specifications"
  ON public.product_specs
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.products
      JOIN public.sellers ON sellers.id = products.seller_id
      WHERE products.id = product_specs.product_id
        AND sellers.profile_id = auth.uid()
        AND sellers.status = 'approved'
    )
  );

CREATE POLICY "Approved sellers can update own product specifications"
  ON public.product_specs
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.products
      JOIN public.sellers ON sellers.id = products.seller_id
      WHERE products.id = product_specs.product_id
        AND sellers.profile_id = auth.uid()
        AND sellers.status = 'approved'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.products
      JOIN public.sellers ON sellers.id = products.seller_id
      WHERE products.id = product_specs.product_id
        AND sellers.profile_id = auth.uid()
        AND sellers.status = 'approved'
    )
  );

CREATE POLICY "Approved sellers can delete own product specifications"
  ON public.product_specs
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.products
      JOIN public.sellers ON sellers.id = products.seller_id
      WHERE products.id = product_specs.product_id
        AND sellers.profile_id = auth.uid()
        AND sellers.status = 'approved'
    )
  );

CREATE POLICY "Platform admins can manage product specifications"
  ON public.product_specs
  FOR ALL
  TO authenticated
  USING (public.is_seller_platform_admin())
  WITH CHECK (public.is_seller_platform_admin());

GRANT SELECT ON public.product_specs TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.product_specs TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.product_specs_id_seq TO authenticated;

COMMENT ON TABLE public.product_specs IS
  'Ordered, seller-defined metadata for digital products; file metadata belongs in product_files.';

COMMIT;
